CAF-3178: Switching to DocumentWorker (worker-javascript) implementat…
CAFDataProcessing/data-processing-service pull request #11
Opened 2017-07-03 15:49 UTC by pcrookshpe

…ion of Markup Worker.

2017-07-07 08:04 UTC, mmaBel commented
I was mistaken on what the Action will contain. The Action should define the set of fields that are required for Markup. This will be the combined fields required from the previous four buckets into a single list of fields.

2017-07-07 10:01 UTC, mmaBel requested changes

2017-07-07 10:01 UTC, mmaBel commented on utils/data-processing-task-submitter-container/base-data/example_workflow.json
> +                          "conversationtopic",
There are more fields that should be here right?

2017-08-15 11:07 UTC, Anthony-McGreevy requested changes
I'm not sure all of these workers should be in the open source workflow

2017-08-15 11:07 UTC, Anthony-McGreevy commented on utils/data-processing-task-submitter-container/base-data/example_workflow.json
> +        "name": "TextExtract",
should the open source stuff have text extract in it since it is licensed?

2017-08-15 11:07 UTC, Anthony-McGreevy commented on utils/data-processing-task-submitter-container/base-data/example_workflow.json
> +        "description": "Extract Metadata and Content of Child Documents and perform Inheritance.",
also requires a license?

2017-08-22 14:07 UTC, merged