CAF-3295: Adding support to initialization code to remove previously initialized data.
CAFDataProcessing/data-processing-service pull request #16
Opened 2017-07-31 18:45 UTC by mmaBel

CAF-3295: Add support to initialization code to remove existing processing workflows, classification workflows, boilerplate expressions and tags before creating new entries based on their names matching the values to use in creation. Task submitter updated to support controlling this via an environment variable. Default behavior is to remove those existing entities that match.

2017-08-03 10:23 UTC, pcrookshpe requested changes
Just a few minor comments - nothing structural.

2017-08-03 10:23 UTC, pcrookshpe commented on release-notes-1.3.0.md
> +  The initialization library classes for processing, classification and boilerplate all support the overwriteExisting property when creating entities through the classes. Default behaviour when the p
Tiny point, but missing a 'T' in CAF\_TASKSUBMIT**T**ER\_BASEDATA\_OVERWRITE\_EXISTING

2017-08-03 10:23 UTC, pcrookshpe commented on utils/data-processing-initialization/src/main/java/com/github/cafdataprocessing/utilities/initialization/WorkflowInitializationParams.java
> +            if(workflowBaseDataFileName==null || workflowBaseDataFileName==""){
Could use Strings.isNullOrEmpty()

2017-08-03 10:23 UTC, pcrookshpe commented on utils/data-processing-initialization/src/main/java/com/github/cafdataprocessing/utilities/initialization/WorkflowInitializationParams.java
> +            if(workflowOverlayFileName==null || workflowOverlayFileName==""){
Ditto.

2017-08-03 10:23 UTC, pcrookshpe commented on utils/data-processing-initialization/src/main/java/com/github/cafdataprocessing/utilities/initialization/WorkflowRemover.java
> +    public static void removeMatchingWorkflows(ProcessingApisProvider apisProvider, String projectId,
Run a static code analysis to check for line length, use of "final" qualifier on parameters and local variables, etc.

2017-08-03 10:23 UTC, pcrookshpe commented on utils/data-processing-initialization/src/main/java/com/github/cafdataprocessing/utilities/initialization/WorkflowRemover.java
> +            LOGGER.info("Workflow name to use in checking existing processing workflows to remove cannot be null. Workflows will not be checked.");
Should this be at least a warning rather than info?

2017-08-03 10:23 UTC, pcrookshpe commented on utils/data-processing-initialization/src/main/java/com/github/cafdataprocessing/utilities/initialization/WorkflowRemover.java
> +        List<ExistingWorkflow> existingWorkflows = new ArrayList<>();
The retrieval of existing workflows could be extracted to another method.

2017-08-03 10:23 UTC, pcrookshpe commented on utils/data-processing-initialization/src/main/java/com/github/cafdataprocessing/utilities/initialization/WorkflowRemover.java
> +            if(existingWorkflow.getName().equals(workflowNameToRemove)){
Should this be case-insensitive?

2017-08-03 10:23 UTC, pcrookshpe commented on utils/data-processing-initialization/src/main/java/com/github/cafdataprocessing/utilities/initialization/WorkflowRemover.java
> +                workflowsApi.deleteWorkflow(projectId, existingWorkflowId);
Is there no single call that can be made to remove a workflow and its processing rules together - e.g. what if processing rules are removed but workflow removal encounters an error?

2017-08-03 10:23 UTC, pcrookshpe commented on utils/data-processing-task-submitter/README.md
> +#### CAF_TASKSUBMITER_BASEDATA_OVERWRITE_EXISTING
Missing 'T'.

2017-08-03 10:23 UTC, pcrookshpe commented on utils/data-processing-task-submitter/src/main/java/com/github/cafdataprocessing/utilities/tasksubmitter/properties/TaskSubmitterProperties.java
> +            public static final String OVERWRITE_EXISTING = "CAF_TASKSUBMITER_BASEDATA_OVERWRITE_EXISTING";
'T'

2017-08-04 08:05 UTC, mmaBel commented on utils/data-processing-initialization/src/main/java/com/github/cafdataprocessing/utilities/initialization/WorkflowRemover.java
> +                workflowsApi.deleteWorkflow(projectId, existingWorkflowId);
No single call exists. An incident to add one was raised previously; https://jira.autonomy.com/browse/CAF-1436.

If the rules were removed but the workflow part failed then removal would throw an exception and on the next attempt the workflow would be removed.

2017-08-04 08:05 UTC, mmaBel commented on utils/data-processing-task-submitter/README.md
> +#### CAF_TASKSUBMITER_BASEDATA_OVERWRITE_EXISTING
Done.

2017-08-04 08:05 UTC, mmaBel commented on utils/data-processing-task-submitter/src/main/java/com/github/cafdataprocessing/utilities/tasksubmitter/properties/TaskSubmitterProperties.java
> +            public static final String OVERWRITE_EXISTING = "CAF_TASKSUBMITER_BASEDATA_OVERWRITE_EXISTING";
Done.

2017-08-04 08:05 UTC, mmaBel commented on utils/data-processing-initialization/src/main/java/com/github/cafdataprocessing/utilities/initialization/WorkflowRemover.java
> +        List<ExistingWorkflow> existingWorkflows = new ArrayList<>();
Done.

2017-08-04 08:06 UTC, mmaBel commented on utils/data-processing-initialization/src/main/java/com/github/cafdataprocessing/utilities/initialization/WorkflowRemover.java
> +            LOGGER.info("Workflow name to use in checking existing processing workflows to remove cannot be null. Workflows will not be checked.");
Seems fair to bump the level up. Changed it.

2017-08-04 08:06 UTC, mmaBel commented on utils/data-processing-initialization/src/main/java/com/github/cafdataprocessing/utilities/initialization/WorkflowInitializationParams.java
> +            if(workflowOverlayFileName==null || workflowOverlayFileName==""){
Done.

2017-08-04 08:06 UTC, mmaBel commented on utils/data-processing-initialization/src/main/java/com/github/cafdataprocessing/utilities/initialization/WorkflowInitializationParams.java
> +            if(workflowBaseDataFileName==null || workflowBaseDataFileName==""){
Done.

2017-08-04 08:06 UTC, mmaBel commented on release-notes-1.3.0.md
> +  The initialization library classes for processing, classification and boilerplate all support the overwriteExisting property when creating entities through the classes. Default behaviour when the p
Changed.

2017-08-04 09:14 UTC, merged