CAF-3056
CAFDataProcessing/data-processing-service pull request #4
Opened 2017-06-09 14:41 UTC by Anthony-McGreevy

2017-06-12 15:33 UTC, kploch requested changes

2017-06-12 15:33 UTC, kploch commented on utils/data-processing-cloud-based-task-submitter/src/main/java/com/github/cafdataprocessing/utilities/cloudbasedtasksubmitter/Main.java
> +        System.exit(0);
Isn't that default? i.e. System.exit(0)?

2017-06-12 15:33 UTC, kploch commented on utils/data-processing-cloud-based-task-submitter/src/main/java/com/github/cafdataprocessing/utilities/cloudbasedtasksubmitter/Main.java
> +        final String ROOT_REFERENCE = getEnvironmentValue(CloudTaskSubmitterConstants.ROOT_REFERENCE);
Naming convention for variables....

2017-06-12 15:33 UTC, kploch commented on utils/data-processing-family-task-submitter/nbactions.xml
> +<?xml version="1.0" encoding="UTF-8"?>
I don't think this file should be in here... It's just some Netbeans project file, right? Update gitignore.

2017-06-12 15:33 UTC, kploch commented on utils/data-processing-family-task-submitter/dependency-reduced-pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This shouldn't be checked in. Please update gitignore file.

2017-06-12 15:33 UTC, kploch commented on utils/data-processing-family-task-submitter/src/main/java/com/github/cafdataprocessing/utilities/familytasksubmitter/CloudTaskSubmitterConstants.java
> +/*
Rename the file to Family...

2017-06-12 15:33 UTC, kploch commented on utils/data-processing-family-task-submitter/src/main/java/com/github/cafdataprocessing/utilities/familytasksubmitter/Main.java
> +        final String ROOT_REFERENCE = getEnvironmentValue(CloudTaskSubmitterConstants.ROOT_REFERENCE);
Naming convention for variables....

2017-06-12 15:33 UTC, kploch commented on utils/data-processing-family-task-submitter/src/main/java/com/github/cafdataprocessing/utilities/familytasksubmitter/Main.java
> +        final DocumentExtractor docBuilder = new DocumentExtractor(familyJson);
If I'm reading the code right then you're getting a map of documents with fields in ElasticQuery class, then convert it to json and convert the json to map again in DocumentExtractor....

2017-06-12 15:33 UTC, kploch commented on utils/data-processing-family-task-submitter/src/main/java/com/github/cafdataprocessing/utilities/familytasksubmitter/elasticsearch/ElasticQuery.java
> +    public JSONObject createFamilyJson(final String filename)
Why do you not just convert the hits and it's fields to Map<String,Multimap<String, String>>? You have fields and references...

2017-06-12 15:33 UTC, kploch commented on utils/data-processing-family-task-submitter/src/main/java/com/github/cafdataprocessing/utilities/familytasksubmitter/elasticsearch/ElasticQuery.java
> +        this.ROOT_REFERENCE = ROOT_REFERENCE;
Field naming convention! ALL_CAPS is for constants only...

2017-06-15 09:33 UTC, kploch requested changes

2017-06-15 09:33 UTC, kploch commented on utils/data-processing-family-task-submitter/src/main/java/com/github/cafdataprocessing/utilities/familytasksubmitter/Main.java
> +        final String rootReference = getEnvironmentValue(FamilyTaskSubmitterConstants.ROOT_REFERENCE);
It should be possible to supply a reference with arguments. Environment variable here is not a good idea. If, let's say a script wanted to call this app, it'd need to set env variable each time before calling the application. It's not a configuration option. It's an execution parameter

2017-06-19 11:04 UTC, kploch requested changes

2017-06-19 11:04 UTC, kploch commented on utils/pom.xml
> +        <module>data-processing-cloud-based-task-submitter</module>
This should be renamed....

2017-06-19 11:04 UTC, kploch commented on utils/data-processing-family-task-submitter/ReadMe.md
> +##Data-Processing-Cloud-Based-Task-Submitter
This should be renamed. All instances of "Cloud" should be renamed.

2017-06-19 11:04 UTC, kploch commented on utils/data-processing-family-task-submitter/pom.xml
> +                            <mainClass>com.github.cafdataprocessing.utilities.cloudbasedtasksubmitter.Main</mainClass>
Wrong....

2017-06-19 11:18 UTC, Anthony-McGreevy commented
@kploch Updated to reflect comments

2017-06-19 13:31 UTC, merged