SCMOD-4732: modifications to the integration tests
CAFDataProcessing/data-processing-service pull request #54
Opened 2018-08-08 15:45 UTC by davidegph

* moved 2 test to global config class
* added 2 tests, one to check cases when global, tenant and repo key did not exist, and another to test get effective repo with non existing keys

http://sou-jenkins2.hpeswlab.net/job/CAFDataProcessing/job/CAFDataProcessing%7Edata-processing-service%7ESCMOD-4732-test%7ECI/2/

2018-08-08 15:51 UTC, michael-bryson requested changes

2018-08-08 15:51 UTC, michael-bryson commented on processing-service-container/src/test/java/com/github/cafdataprocessing/processing/service/tests/RepositoryConfigIT.java
> +    @Test(description = "Test that 404 is returned if the key, tenantId and repositoryId are all non-existing")
I think this one should be split into 3 tests, each one checking that you get a 404 if one of the parameter values do not exist while the others do exist in each test. Therefore 3 tests:
- key not exist, tenantId and repositoryId do exist
- tenantId not exist, key and repositoryId do exist
- repositoryId not exist, key and tenantId do exist

2018-08-08 17:24 UTC, davidegph commented
Build succeeded also after the new tests have been added

http://sou-jenkins2.hpeswlab.net/job/CAFDataProcessing/job/CAFDataProcessing%7Edata-processing-service%7ESCMOD-4732-test%7ECI/3/

2018-08-09 08:13 UTC, michael-bryson approved these changes

2018-08-09 08:14 UTC, merged