SCMOD-4829: fixed 2 bugs
CAFDataProcessing/data-processing-service pull request #56
Opened 2018-09-19 11:33 UTC by davidegph

* scope in the global configuration cannot be changed anymore if a repository configuration exists and uses its key
* a tenant configuration cannot be deleted anymore if a repository configuration exists and uses its tenant id
* added 2 tests to verify these behaviors

2018-09-19 13:01 UTC, davidegph commented
Hi Dermot,

would you mind review this pull request, please?

2018-09-19 21:54 UTC, dermot-hardy commented
I'm quite confused about the second point:
> a tenant configuration cannot be deleted anymore if a repository configuration exists and uses its tenant id

I'm not sure that we should be disallowing this.  It's not clear to me why we are.  Was there a conversation about this that I've forgotten?  The Jira only covers the first point which is clearly a bug.  But on this second point surely you could easily get into the same state by adding a repository configuration for a setting that hasn't been set at the tenant level - so I don't understand why we're doing that.

2018-09-19 21:55 UTC, dermot-hardy requested changes
I'm quite confused about the second point:
> a tenant configuration cannot be deleted anymore if a repository configuration exists and uses its tenant id

I'm not sure that we should be disallowing this.  It's not clear to me why we are.  Was there a conversation about this that I've forgotten?  The Jira only covers the first point which is clearly a bug.  But on this second point surely you could easily get into the same state by adding a repository configuration for a setting that hasn't been set at the tenant level - so I don't understand why we're doing that.

2018-09-20 14:54 UTC, davidegph commented
Hi @dermot-hardy ,

I misunderstood the fact that a tenant configuration should have always been present to have a configuration for a repository. I have removed this part, and now the code only allows to spot the change of scope in the global configuration, as mentioned in the jira.

I managed to [build it](http://sou-jenkins2.hpeswlab.net/job/CAFDataProcessing/job/CAFDataProcessing%7Edata-processing-service%7ESCMOD-4829%7ECI/17/) too.

2018-09-24 00:47 UTC, dermot-hardy commented on processing-service-container/src/test/java/com/github/cafdataprocessing/processing/service/tests/RepositoryConfigIT.java
> +        TENANT_API.deleteTenantConfigs(tenantId);
Why is this change required?

2018-09-24 00:48 UTC, dermot-hardy approved these changes

2018-09-25 09:54 UTC, Anthony-McGreevy approved these changes

2018-09-25 10:48 UTC, merged